import { BREAK } from "../../repository/consts/course.const";

export const cohorts = [
  {
    program: "DMA",
    name: "E1-0324",
    room: "Facebook",
    time: "Evening",
    intake: "March 2024",
    studentCount: 10,
    schedules: [
      {
        startDate: "2024-03-04",
        endDate: "2024-03-29",
        course: "Advanced SEO",
        days: "Monday - Wednesday",
        instructor: "Alex",
      },
      {
        startDate: "2024-03-04",
        endDate: "2024-03-29",
        course: "Advanced Strategies",
        days: "Wednesday - Friday",
        instructor: "John",
      },
      {
        startDate: "2024-04-01",
        endDate: "2024-04-26",
        course: "Automation",
        days: "Monday - Friday",
        instructor: "John",
      },
      {
        startDate: "2024-04-29",
        endDate: "2024-06-07",
        course: "Content Creation",
        days: "Monday - Friday",
        instructor: "John",
      },
      {
        startDate: "2024-06-10",
        endDate: "2024-06-21",
        course: "Digital Ads",
        days: "Monday - Friday",
        instructor: "John",
      },
      {
        startDate: "2024-06-24",
        endDate: "2024-07-05",
        course: BREAK,
        days: "Monday - Friday",
        instructor: null,
      },
      {
        startDate: "2024-07-08",
        endDate: "2024-08-02",
        course: "Ecommerce",
        days: "Monday - Friday",
        instructor: "John",
      },
    ],
  },
  {
    program: "DMA",
    name: "E2-0324",
    room: "Youtube",
    time: "Evening",
    intake: "March 2024",
    studentCount: 10,
    schedules: [
      {
        startDate: "2024-03-04",
        endDate: "2024-03-29",
        course: "Advanced SEO",
        days: "Wednesday - Friday",
        instructor: "Alex",
      },
      {
        startDate: "2024-03-04",
        endDate: "2024-03-29",
        course: "Advanced Strategies",
        days: "Monday - Wednesday",
        instructor: "John",
      },
      {
        startDate: "2024-04-01",
        endDate: "2024-04-26",
        course: "Automation",
        days: "Monday - Friday",
        instructor: "Alex",
      },
      {
        startDate: "2024-04-29",
        endDate: "2024-06-07",
        course: "Content Creation",
        days: "Monday - Friday",
        instructor: "Alex",
      },
      {
        startDate: "2024-06-10",
        endDate: "2024-06-21",
        course: "Digital Ads",
        days: "Monday - Friday",
        instructor: "Alex",
      },
      {
        startDate: "2024-06-24",
        endDate: "2024-07-05",
        course: BREAK,
        days: "Monday - Friday",
        instructor: null,
      },
      {
        startDate: "2024-07-08",
        endDate: "2024-08-02",
        course: "Ecommerce",
        days: "Monday - Friday",
        instructor: "Alex",
      },
    ],
  },
  {
    program: "DMS",
    name: "M1-0324",
    room: "Amazon",
    time: "Morning",
    intake: "March 2024",
    studentCount: 10,
    schedules: [
      {
        startDate: "2024-03-04",
        endDate: "2024-03-29",
        course: "Analytics",
        days: "Monday - Friday",
        instructor: "Mariam",
      },
      {
        startDate: "2024-04-01",
        endDate: "2024-04-26",
        course: "Campaign Management",
        days: "Monday - Friday",
        instructor: "Mariam",
      },
      {
        startDate: "2024-04-29",
        endDate: "2024-05-24",
        course: "Design",
        days: "Monday - Friday",
        instructor: "Mariam",
      },
      {
        startDate: "2024-05-27",
        endDate: "2024-06-21",
        course: "Digital Marketing 1",
        days: "Monday - Friday",
        instructor: "Mariam",
      },
      {
        startDate: "2024-06-24",
        endDate: "2024-07-19",
        course: "Digital Marketing 2",
        days: "Monday - Friday",
        instructor: "Mariam",
      },
      {
        startDate: "2024-07-22",
        endDate: "2024-08-09",
        course: BREAK,
        days: "Monday - Friday",
        instructor: null,
      },
      {
        startDate: "2024-08-12",
        endDate: "2024-08-23",
        course: "SEO",
        days: "Monday - Friday",
        instructor: "Mariam",
      },
      {
        startDate: "2024-08-26",
        endDate: "2024-09-20",
        course: "Social Media",
        days: "Monday - Wednesday",
        instructor: "Brian",
      },
      {
        startDate: "2024-08-26",
        endDate: "2024-09-20",
        course: "WordPress",
        days: "Wednesday - Friday",
        instructor: "Mariam",
      },
    ],
  },
  {
    program: "DMS",
    name: "M2-0324",
    room: "Google",
    time: "Morning",
    intake: "March 2024",
    studentCount: 10,
    schedules: [
      {
        startDate: "2024-03-04",
        endDate: "2024-03-29",
        course: "Analytics",
        days: "Monday - Friday",
        instructor: "Brian",
      },
      {
        startDate: "2024-04-01",
        endDate: "2024-04-26",
        course: "Campaign Management",
        days: "Monday - Friday",
        instructor: "Brian",
      },
      {
        startDate: "2024-04-29",
        endDate: "2024-05-24",
        course: "Design",
        days: "Monday - Friday",
        instructor: "Brian",
      },
      {
        startDate: "2024-05-27",
        endDate: "2024-06-21",
        course: "Digital Marketing 1",
        days: "Monday - Friday",
        instructor: "Brian",
      },
      {
        startDate: "2024-06-24",
        endDate: "2024-07-19",
        course: "Digital Marketing 2",
        days: "Monday - Friday",
        instructor: "Brian",
      },
      {
        startDate: "2024-07-22",
        endDate: "2024-08-09",
        course: BREAK,
        days: "Monday - Friday",
        instructor: null,
      },
      {
        startDate: "2024-08-12",
        endDate: "2024-08-23",
        course: "SEO",
        days: "Monday - Friday",
        instructor: "Brian",
      },
      {
        startDate: "2024-08-26",
        endDate: "2024-09-20",
        course: "Social Media",
        days: "Monday - Wednesday",
        instructor: "Brian",
      },
      {
        startDate: "2024-08-26",
        endDate: "2024-09-20",
        course: "WordPress",
        days: "Wednesday - Friday",
        instructor: "Mariam",
      },
    ],
  },
  {
    program: "DMA",
    name: "A1-1024",
    room: "Microsoft",
    time: "Afternoon",
    intake: "October 2024",
    studentCount: 10,
    schedules: [
      {
        startDate: "2024-09-30",
        endDate: "2024-10-11",
        course: "Advanced SEO",
        days: "Monday - Friday",
        instructor: "John",
      },
      {
        startDate: "2024-10-14",
        endDate: "2024-10-25",
        course: "Advanced Strategies",
        days: "Monday - Friday",
        instructor: "Jennifer",
      },
      {
        startDate: "2024-10-28",
        endDate: "2024-11-22",
        course: "Automation",
        days: "Monday - Friday",
        instructor: "John",
      },
      {
        startDate: "2024-11-25",
        endDate: "2024-12-20",
        course: "Content Creation",
        days: "Monday - Friday",
        instructor: "John",
      },
      {
        startDate: "2024-12-23",
        endDate: "2025-01-03",
        course: BREAK,
        days: "Monday - Friday",
        instructor: null,
      },
      {
        startDate: "2025-01-06",
        endDate: "2025-01-17",
        course: "Content Creation",
        days: "Monday - Friday",
        instructor: "John",
      },
      {
        startDate: "2025-01-20",
        endDate: "2025-01-31",
        course: "Digital Ads",
        days: "Monday - Friday",
        instructor: "John",
      },
      {
        startDate: "2025-02-03",
        endDate: "2025-02-28",
        course: "Ecommerce",
        days: "Monday - Friday",
        instructor: "John",
      },
    ],
  },
  {
    program: "DMS",
    name: "A2-1024",
    room: "Apple",
    time: "Afternoon",
    intake: "October 2024",
    studentCount: 10,
    schedules: [
      {
        startDate: "2024-09-30",
        endDate: "2024-10-25",
        course: "Analytics",
        days: "Monday - Friday",
        instructor: "Thomas",
      },
      {
        startDate: "2024-10-28",
        endDate: "2024-11-22",
        course: "Campaign Management",
        days: "Monday - Friday",
        instructor: "Thomas",
      },
      {
        startDate: "2024-11-25",
        endDate: "2024-12-20",
        course: "Design",
        days: "Monday - Friday",
        instructor: "Brian",
      },
      {
        startDate: "2024-12-23",
        endDate: "2025-01-03",
        course: BREAK,
        days: "Monday - Friday",
        instructor: null,
      },
      {
        startDate: "2025-01-06",
        endDate: "2025-01-31",
        course: "Digital Marketing 1",
        days: "Monday - Friday",
        instructor: "Brian",
      },
      {
        startDate: "2025-02-03",
        endDate: "2025-02-28",
        course: "Digital Marketing 2",
        days: "Monday - Friday",
        instructor: "Brian",
      },
      {
        startDate: "2025-03-03",
        endDate: "2025-03-14",
        course: "SEO",
        days: "Monday - Friday",
        instructor: "Brian",
      },
      {
        startDate: "2025-03-17",
        endDate: "2025-04-11",
        course: "Social Media",
        days: "Monday - Wednesday",
        instructor: "Brian",
      },
      {
        startDate: "2025-03-17",
        endDate: "2025-04-11",
        course: "WordPress",
        days: "Wednesday - Friday",
        instructor: "Mariam",
      },
    ],
  },
];
