export const users = [
  {
    firstName: "Mariam",
    lastName: "",
    role: "instructor",
    avatarUrl: "https://randomuser.me/api/portraits/women/26.jpg",
    email: "instructor.mariam@gmail.com",
    password: "$2b$10$ySaYRgMVgNFkNLCDu2iqiO3mGctKCvhL/o56vvrZr.PpnjcOQwJCq",
    hourType: "full",
    isActive: true,
    userCapabilityDays: ["Monday - Friday", "Monday - Wednesday", "Wednesday - Friday"],
    userCapabilityTimes: ["Evening", "Morning", "Afternoon"],
    userCapabilityCourses: [
      "Analytics",
      "Campaign Management",
      "Design",
      "Digital Marketing 1",
      "Digital Marketing 2",
      "SEO",
      "Social Media",
      "WordPress",
    ],
    userPrograms: ["DMS"],
  },
  {
    firstName: "Brian",
    lastName: "",
    role: "instructor",
    avatarUrl: "https://randomuser.me/api/portraits/men/20.jpg",
    email: "instructor.brian@gmail.com",
    password: "$2b$10$ySaYRgMVgNFkNLCDu2iqiO3mGctKCvhL/o56vvrZr.PpnjcOQwJCq",
    hourType: "full",
    isActive: true,
    userCapabilityDays: ["Monday - Friday", "Monday - Wednesday", "Wednesday - Friday"],
    userCapabilityTimes: ["Morning"],
    userCapabilityCourses: [
      "Analytics",
      "Campaign Management",
      "Design",
      "Digital Marketing 1",
      "Digital Marketing 2",
      "SEO",
      "Social Media",
      //"WordPress",
    ],
    userPrograms: ["DMS"],
  },
  {
    firstName: "Thomas",
    lastName: "",
    role: "instructor",
    avatarUrl: "https://randomuser.me/api/portraits/men/26.jpg",
    email: "instructor.thomas@gmail.com",
    password: "$2b$10$ySaYRgMVgNFkNLCDu2iqiO3mGctKCvhL/o56vvrZr.PpnjcOQwJCq",
    hourType: "full",
    isActive: true,
    userCapabilityDays: ["Monday - Friday", "Monday - Wednesday", "Wednesday - Friday"],
    userCapabilityTimes: ["Morning", "Afternoon"],
    userCapabilityCourses: [
      "Analytics",
      "Campaign Management",
      "Design",
      "Digital Marketing 1",
      "Digital Marketing 2",
      "SEO",
      "Social Media",
      "WordPress",
    ],
    userPrograms: ["DMS"],
  },
  {
    firstName: "Alex",
    lastName: "",
    role: "instructor",
    avatarUrl: "https://randomuser.me/api/portraits/men/22.jpg",
    email: "instructor.alex@gmail.com",
    password: "$2b$10$ySaYRgMVgNFkNLCDu2iqiO3mGctKCvhL/o56vvrZr.PpnjcOQwJCq",
    hourType: "part",
    isActive: true,
    userCapabilityDays: ["Monday - Friday", "Monday - Wednesday", "Wednesday - Friday"],
    userCapabilityTimes: ["Evening"],
    userCapabilityCourses: [
      "Advanced SEO",
      //"Advanced Strategies",
      "Automation",
      "Content Creation",
      "Digital Ads",
      "Ecommerce",
    ],
    userPrograms: ["DMA"],
  },
  {
    firstName: "Jennifer",
    lastName: "",
    role: "instructor",
    avatarUrl: "https://randomuser.me/api/portraits/women/22.jpg",
    email: "instructor.jennifer@gmail.com",
    password: "$2b$10$ySaYRgMVgNFkNLCDu2iqiO3mGctKCvhL/o56vvrZr.PpnjcOQwJCq",
    hourType: "part",
    isActive: true,
    userCapabilityDays: ["Monday - Friday", "Monday - Wednesday", "Wednesday - Friday"],
    userCapabilityTimes: ["Afternoon", "Evening"],
    userCapabilityCourses: [
      //"Advanced SEO",
      "Advanced Strategies",
      "Automation",
      "Content Creation",
      //"Digital Ads",
      "Ecommerce",
    ],
    userPrograms: ["DMA"],
  },
  {
    firstName: "John",
    lastName: "",
    role: "instructor",
    avatarUrl: "https://randomuser.me/api/portraits/men/28.jpg",
    email: "instructor.john@gmail.com",
    password: "$2b$10$ySaYRgMVgNFkNLCDu2iqiO3mGctKCvhL/o56vvrZr.PpnjcOQwJCq",
    hourType: "part",
    isActive: true,
    userCapabilityDays: ["Monday - Friday", "Monday - Wednesday", "Wednesday - Friday"],
    userCapabilityTimes: ["Morning", "Afternoon", "Evening"],
    userCapabilityCourses: [
      "Analytics",
      "Campaign Management",
      //"Design",
      "Digital Marketing 1",
      "Digital Marketing 2",
      "SEO",
      "Social Media",
      //"WordPress",
      "Advanced SEO",
      "Advanced Strategies",
      "Automation",
      "Content Creation",
      "Digital Ads",
      "Ecommerce",
    ],
    userPrograms: ["DMS", "DMA"],
  },
  {
    firstName: "AllMight",
    lastName: "",
    role: "instructor",
    avatarUrl: "https://image-me.s3.us-west-2.amazonaws.com/user.png",
    email: "instructor.allmight@gmail.com",
    password: "$2b$10$ySaYRgMVgNFkNLCDu2iqiO3mGctKCvhL/o56vvrZr.PpnjcOQwJCq",
    hourType: "contract",
    isActive: true,
    userCapabilityDays: ["Monday - Friday", "Monday - Wednesday", "Wednesday - Friday"],
    userCapabilityTimes: ["Morning", "Afternoon", "Evening"],
    userCapabilityCourses: [
      "Analytics",
      "Campaign Management",
      "Design",
      "Digital Marketing 1",
      "Digital Marketing 2",
      "SEO",
      "Social Media",
      "WordPress",
      "Advanced SEO",
      "Advanced Strategies",
      "Automation",
      "Content Creation",
      "Digital Ads",
      "Ecommerce",
    ],
    userPrograms: ["DMS", "DMA"],
  },
  {
    firstName: "Rodrigo",
    lastName: "",
    role: "manager",
    avatarUrl: "https://randomuser.me/api/portraits/men/50.jpg",
    email: "manager.rodrigo@gmail.com",
    password: "$2b$10$ySaYRgMVgNFkNLCDu2iqiO3mGctKCvhL/o56vvrZr.PpnjcOQwJCq",
    hourType: "full",
    isActive: true,
    userCapabilityDays: [],
    userCapabilityTimes: [],
    userCapabilityCourses: [],
    userPrograms: ["DMS", "DMA"],
  },
];
