name: CI-backend

on:
  pull_request:
    branches:
      - development
    paths:
      - 'backend/**'
      - 'shared/**'
      - 'aws-cdk/backend/**'
    types:
      - opened
      - synchronize

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 20

      - name: Install dependencies
        run: |
          cd backend && npm ci

      - name: Build Nest.js app
        run: |
          cd backend && npm run build

      - name: Clean up
        run: |
          npm prune --production
